package com.humanperformcenter.app.navigation

sealed class Screen(val route: String) {
    data object WelcomeScreen : Screen("welcome")
    data object RegisterScreen : Screen("register")
    data object LoginScreen : Screen("login")
    data object NewProductScreen : Screen("new_product")
    data object CalendarScreen : Screen("calendar")
    data object NewBlogScreen : Screen("new_blog")
    data object UserScreen : Screen("user")
    data object EditProfileScreen : Screen("edit_profile")
    data object FavoritesScreen : Screen("favorites")
    data object ChatScreen : Screen("chat")
    data object DocumentScreen : Screen("document")
    data object PaymentScreen : Screen("payment")
    data object ViewPaymentScreen : Screen("view_payment")
    data object EntrenamientoScreen : Screen("entrenamiento_screen")
    data object NutricionScreen : Screen("nutricion_screen")
    data object FisioterapiaScreen : Screen("fisioterapia_screen")
    data object PilatesScreen : Screen("pilates_screen")
    data object PresoterapiaScreen : Screen("presoterapia_screen")
    data object OpositoresScreen : Screen("opositores_screen")
    data object TaquillaScreen : Screen("taquilla_screen")
    data object AlterGScreen : Screen("alterg_screen")
}
